### ISSUE TITLE
thin-long 행렬과 long-thin 행렬의 곱셈 성능 측정

### ISSUE THREAD

**Issue by hyu-leeky** [kmu-bigdata/distributed-matrix-completion#2]
스파크 MLLib 활용
매트릭스 사이즈는
1M * 1K   정도로
block 나누는 법은 행별, 열별, 블락별을 각각 따로 시도해봐야 할듯

**Comment by namnam21** [comment]
test1 (초기에 동일한 블럭개수에서 numMidDimSplits 값만 바꾼 경우)
val leftRowParallelism = 2, leftColParallelism = 8
val rightRowParallelism = 8, rightColParallelism = 2
val rowBlockSize = 1024, colBlockSize = 1024

val leftRows = 2048, leftCols = 8192
val rightRows = 8192, rightCols = 2048

val leftRowBlocks = 2, leftColBlocks = 8
val rightRowBlocks = 8, rightColBlocks = 2

numMidDimSplits=1
![image](https://user-images.githubusercontent.com/22073662/26969957-8892b11a-4d42-11e7-8b45-c012acccd2b1.png)
numMidDimSplits=4

![image](https://user-images.githubusercontent.com/22073662/26969968-948b9f90-4d42-11e7-8647-0560c7cce95b.png)

Screen shot - Job4 
numMidDimSplits=1

![image](https://user-images.githubusercontent.com/22073662/26969978-9c9a9772-4d42-11e7-90f6-88c6f651a1c2.png)
numMidDimSplits=4
![image](https://user-images.githubusercontent.com/22073662/26969986-a22075cc-4d42-11e7-9760-161fe055ba3c.png)

**Comment by namnam21** [comment]
test2 
val rowBlockSize = 512, colBlockSize = 512
val leftRows = 2048, leftCols = 8192
val rightRows = 8192, rightCols = 2048
val leftRowBlocks = 4, leftCol Blocks = 16
val rightRowBlocks = 16, rightColBlocks = 4
numMidDimSplits=1

![image](https://user-images.githubusercontent.com/22073662/26970103-0d3e5a2c-4d43-11e7-941d-300105d62b7a.png)

val rowBlockSize = 1024, colBlockSize = 1024
val leftRows = 2048, leftCols = 8192
val rightRows = 8192, rightCols = 2048
val leftRowBlocks = 2, leftColBlocks = 8
val rightRowBlocks = 8, rightColBlocks = 2
numMidDimSplits=4

![image](https://user-images.githubusercontent.com/22073662/26970111-12742bfc-4d43-11e7-9461-a2e751c89441.png)

Screen shot - Job4 
numMidDimSplits=1

![image](https://user-images.githubusercontent.com/22073662/26970118-169941cc-4d43-11e7-884a-087dc81f8c54.png)
numMidDimSplits=4

![image](https://user-images.githubusercontent.com/22073662/26970123-1b994e10-4d43-11e7-9425-dc3abc068286.png)
